---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opencti-credentials
  namespace: opencti
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cluster
    kind: ClusterSecretStore
  target:
    name: opencti-credentials
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: "^OPENCTI_"
        path: /opencti
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opencti-rabbitmq-credentials
  namespace: opencti
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cluster
    kind: ClusterSecretStore
  target:
    name: opencti-rabbitmq-credentials
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: "^RABBITMQ_"
        path: /opencti
---
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: opencti-minio-credentials
  namespace: opencti
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: infisical-cluster
    kind: ClusterSecretStore
  target:
    name: opencti-minio-credentials
    creationPolicy: Owner
  dataFrom:
    - find:
        name:
          regexp: "^MINIO_"
        path: /opencti
